#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker11"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "015fb3fdef8e4be6b5cfa604c2eb979b" }
]

[assets]
directory = "./public"
